baseurl      = "localhost"
title        = "Distributed Ideas"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Distributed Databases, Distibuted Systems, Devops specialist."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  enableThemeToggle = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    logoCursorPathname = false

  [[params.social]]
    name = "github"
    url  = "https://github.com/yveyal"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/eyal-yaacov-7900b221/"


[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Eyal Yaacov"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "Distributing ideas ..."

    [languages.en.params.logo]
    #  logoText = "hello friend ng"
    #  logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
#  [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "blog/"
#    weight     = "1"
#  [[menu.main]]
#    identifier = "articles"
#    name       = "Articles"
#   url        = "articles/"
#    weight     = "2"
#  [[menu.main]]
#    identifier = "notes"
#    name       = "Notes"
#   url        = "notes/"
#    weight     = "3"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight     = "4"
#  [[menu.main]]
#    identifier = "appendix"
#    name       = "The rest"
#    weight     = "5"
#    url        = "appendix/"
